name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Secrets einfügen
        run: |
          sed \
            -e "s|%%FIREBASE_API_KEY%%|${{ secrets.FIREBASE_API_KEY }}|g" \
            -e "s|%%FIREBASE_AUTH_DOMAIN%%|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" \
            -e "s|%%FIREBASE_PROJECT_ID%%|${{ secrets.FIREBASE_PROJECT_ID }}|g" \
            -e "s|%%FIREBASE_SENDER_ID%%|${{ secrets.FIREBASE_SENDER_ID }}|g" \
            -e "s|%%FIREBASE_APP_ID%%|${{ secrets.FIREBASE_APP_ID }}|g" \
            index.template.html > index.html

      - name: Auf GitHub Pages deployen
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
