name: Build & Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

     - name: Secrets einfügen
        run: |
          mkdir -p dist
          sed \
            -e "s|%%FIREBASE_API_KEY%%|${{ secrets.FIREBASE_API_KEY }}|g" \
            -e "s|%%FIREBASE_AUTH_DOMAIN%%|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" \
            -e "s|%%FIREBASE_PROJECT_ID%%|${{ secrets.FIREBASE_PROJECT_ID }}|g" \
            -e "s|%%FIREBASE_SENDER_ID%%|${{ secrets.FIREBASE_SENDER_ID }}|g" \
            -e "s|%%FIREBASE_APP_ID%%|${{ secrets.FIREBASE_APP_ID }}|g" \
            index.template.html > dist/index.html

      - name: Auf GitHub Pages deployen
        uses: peaceiris/actions-gh-pages@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
